### ISSUE TITLE
XML syntax errors

### ISSUE THREAD

**Issue by russorat** [DRuggeri/netgear_exporter#1]
Seeing these errors when using the exporter. Maybe netgear updated their xml or something?

I am using a Nighthawk R7000 with firmware version: V1.0.9.64_10.2.64

I didn't see any additional info while using log.level=debug

```
ERRO[0364] Error while collecting system info: XML syntax error on line 4: element <meta> closed by </head>  source="system_info_collector.go:110"
ERRO[0364] Error while collecting traffic statistics: XML syntax error on line 4: element <meta> closed by </head>  source="traffic_collector.go:126"
ERRO[0364] Error while collecting client statistics: XML syntax error on line 4: element <meta> closed by </head>  source="clients_collector.go:122"
```

**Comment by DRuggeri** [comment]
That's very odd... Debug didn't show the full request/response?

I don't know much about the Netgear server side of things, but in my limited experience it has always at least provided valid XML. To see misbalanced tags would make me suspect even the Netgear fat client app would also fail (perhaps worth a try as an added data point?)

**Comment by DRuggeri** [comment]
For now, since I cannot replicate this and I'm not sure we'd be able to deal with it, I'll go ahead and close the issue. Maybe more information can come from the `--clientdebug` parameter to at least identify what's misbalanced, but as mentioned... if Netgear is producing invalid XML, I don't know what the client can do to fix that (short of not parsing it as XML)

**Comment by imrebuild** [comment]
I got the same error. 

While sending request to `http://10.0.0.1/soap/server_sa/`, I got `html` instead of `xml` and the response code is 401.

I'm not sure if it is related to custom url, bacause the `Host` header of request is `routerlogin.net` rather than `10.0.0.1`.

**Comment by DRuggeri** [comment]
Thanks, @imrebuild - does the content of the response indicate anything helpful?

**Comment by imrebuild** [comment]
Sorry I made a mistake. Changing port to 5000 solved this issue.

**Comment by justmiles** [comment]
More context for anyone else dealing with the R7000: Bump the timeout. Although on a local network, the router can take longer than the default 2 seconds to return data. Setting `NETGEAR_EXPORTER_TIMEOUT` to 10 helped here.
