### ISSUE TITLE
Enhancement request for -h or readme

### ISSUE THREAD

**Issue by klein5656** [DRuggeri/netgear_exporter#13]
Hello, Would it be possible to add more details into the help command or readme? 

example would be what need to be set to run the exporter. (maybe its my understanding but feels like it could use more details)
export NETGEAR_EXPORTER_URL="1.1.1.1"
export NETGEAR_EXPORTER_WEB_LISTEN_ADDRESS="localhost:9192"
export NETGEAR_EXPORTER_USERNAME="admin"
export NETGEAR_EXPORTER_PASSWORD=`cat /home/netgear_exporter/.netgear_exporter_password`
export NETGEAR_EXPORTER_INSECURE="true"
export NETGEAR_EXPORTER_TIMEOUT=2
export NETGEAR_EXPORTER_FILTER_COLLECTORS=Client,SystemInfo,Traffic
export NETGEAR_EXPORTER_METRICS_NAMESPACE=netgear

Also maybe a little detail around making it into a services. 

netgear_exporter.service
[Unit]
Description=NETGEAR Exporter

[Service]
Environment="NETGEAR_EXPORTER_URL="1.1.1.1""
Environment="NETGEAR_EXPORTER_WEB_LISTEN_ADDRESS="localhost:9192""
Environment="NETGEAR_EXPORTER_USERNAME="admin""
Environment="NETGEAR_EXPORTER_PASSWORD=`cat /home/netgear_exporter/.netgear_exporter_password`"
Environment="NETGEAR_EXPORTER_INSECURE="true""
Environment="NETGEAR_EXPORTER_TIMEOUT=2"
Environment="NETGEAR_EXPORTER_FILTER_COLLECTORS=Client,SystemInfo,Traffic"
Environment="NETGEAR_EXPORTER_METRICS_NAMESPACE=netgear"
ExecStart=/usr/local/bin/netgear_exporter --url="$NETGEAR_EXPORTER_URL"  --username="$NETGEAR_EXPORTER_USERNAME" --insecure --log.level="debug" --web.listen-address=":9192" --web.telemetry-path="/metrics"

[Install]
WantedBy=multi-user.target

**Comment by DRuggeri** [comment]
Sure, @klein5656 - no problem. I've gone ahead and updated the README in fd0bd4f83a9aea118ad75e3df7512aa1126f83f0. Have a look - I hope it helps!
