### ISSUE TITLE
XML syntax error

### ISSUE THREAD

**Issue by klein5656** [DRuggeri/netgear_exporter#14]
When running the exporter by hand getting an odd exception when the exporter is running. 

/usr/local/bin/netgear_exporter --url="$NETGEAR_EXPORTER_URL"  --username="$NETGEAR_EXPORTER_USERNAME" --insecure --log.level="debug" --web.listen-address=":9192" --web.telemetry-path="/metrics" 
INFO[0000] Starting node_exporter testing                source="netgear_exporter.go:180"
INFO[0000] Listening on :9192                            source="netgear_exporter.go:230"
ERRO[0003] Error while collecting traffic statistics: XML syntax error on line 4: element <meta> closed by </head>  source="traffic_collector.go:126"
ERRO[0003] Error while collecting client statistics: XML syntax error on line 4: element <meta> closed by </head>  source="clients_collector.go:122"
ERRO[0003] Error while collecting system info: XML syntax error on line 4: element <meta> closed by </head>  source="system_info_collector.go:110"
ERRO[0069] Error while collecting traffic statistics: XML syntax error on line 4: element <meta> closed by </head>  source="traffic_collector.go:126"
ERRO[0069] Error while collecting client statistics: XML syntax error on line 4: element <meta> closed by </head>  source="clients_collector.go:122"
ERRO[0069] Error while collecting system info: XML syntax error on line 4: element <meta> closed by </head>  source="system_info_collector.go:110"
ERRO[0070] Error while collecting client statistics: XML syntax error on line 4: element <meta> closed by </head>  source="clients_collector.go:122"
ERRO[0071] Error while collecting system info: XML syntax error on line 4: element <meta> closed by </head>  source="system_info_collector.go:110"
ERRO[0071] Error while collecting traffic statistics: XML syntax error on line 4: element <meta> closed by </head>  source="traffic_collector.go:126"
ERRO[0072] Error while collecting system info: XML syntax error on line 4: element <meta> closed by </head>  source="system_info_collector.go:110"
ERRO[0072] Error while collecting traffic statistics: XML syntax error on line 4: element <meta> closed by </head>  source="traffic_collector.go:126"
ERRO[0072] Error while collecting client statistics: XML syntax error on line 4: element <meta> closed by </head>  source="clients_collector.go:122"

The exporter is up but not sure if this is good or bad.

**Comment by DRuggeri** [comment]
Hi, @klein5656 - this would indicate that the collector is able to reach out to your router, but doesn't seem to like the XML response that came back. Can you share debug logs (being careful to redact any sensitive information)? This seems to be a totally different error message from what is seen in #12 so probably worth examining the debug info.

**Comment by klein5656** [comment]
Hello @DRuggeri,

Here is the output from --clientdebug

root@raspberrypi:/home/netgear_exporter# /usr/local/bin/netgear_exporter --url=https://{router_IP}  --web.auth.username=admin --insecure --timeout=1 --filter.collectors=Traffic  --clientdebug  
INFO[0000] Starting node_exporter testing                source="netgear_exporter.go:180"
2022/12/17 14:30:26 netgear_client.go: Constructing debug client
INFO[0000] Listening on :9192                            source="netgear_exporter.go:230"
2022/12/17 14:30:27 netgear_client.go: full url (derived)='https://{roter_IP}/soap/server_sa/', data='<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<SOAP-ENV:Envelope
  xmlns:SOAPSDK1="http://www.w3.org/2001/XMLSchema"
  xmlns:SOAPSDK2="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:SOAPSDK3="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <SessionID>A7D88AE69687E58D9A00</SessionID>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <M1:GetTrafficMeterStatistics xmlns:M1="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
    </M1:GetTrafficMeterStatistics>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>'
2022/12/17 14:30:27 netgear_client.go: Sending HTTP request to https://{roter_IP}/soap/server_sa/...
2022/12/17 14:30:27 netgear_client.go: Request headers:
2022/12/17 14:30:27 netgear_client.go:   Content-Type: text/xml;charset=utf-8
2022/12/17 14:30:27 netgear_client.go:   Soapaction: urn:NETGEAR-ROUTER:service:DeviceConfig:1#GetTrafficMeterStatistics
2022/12/17 14:30:27 netgear_client.go:   Host: routerlogin.net
2022/12/17 14:30:27 netgear_client.go:   Cookie: UNSET
2022/12/17 14:30:27 netgear_client.go:   Content-Length: 580
2022/12/17 14:30:27 netgear_client.go:   User-Agent: curl/7.59.0
2022/12/17 14:30:27 netgear_client.go: BODY:
2022/12/17 14:30:27 <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<SOAP-ENV:Envelope
  xmlns:SOAPSDK1="http://www.w3.org/2001/XMLSchema"
  xmlns:SOAPSDK2="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:SOAPSDK3="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <SessionID>A7D88AE69687E58D9A00</SessionID>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <M1:GetTrafficMeterStatistics xmlns:M1="urn:NETGEAR-ROUTER:service:DeviceConfig:1">
    </M1:GetTrafficMeterStatistics>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
2022/12/17 14:30:27 netgear_client.go: Response code: 401
2022/12/17 14:30:27 netgear_client.go: Response headers:
2022/12/17 14:30:27 netgear_client.go:   Set-Cookie: XSRF_TOKEN=186932223; Path=/
2022/12/17 14:30:27 netgear_client.go:   Www-Authenticate: Basic realm="NETGEAR R7000"
2022/12/17 14:30:27 netgear_client.go:   Content-Type: text/html
2022/12/17 14:30:27 netgear_client.go:   X-Frame-Options: SAMEORIGIN
ERRO[0001] Error while collecting traffic statistics: XML syntax error on line 4: element <meta> closed by </head>  source="traffic_collector.go:126"


It might just be I have a wrong config

**Comment by DRuggeri** [comment]
Thanks, @klein5656 - this seems to be formatted differently or something. There appears to be several missing `>` and `<` characters in the output. Maybe that's just because GitHub has eaten some of the characters because they weren't captured in a preformtted output. Can you please double-check if that's the case? You can post pre-formatted/code text by using three \` characters in a row on an empty line, then paste the contents and close it out with another three \` characters

Debugging what I can tell, the HTTP response code coming back is a 401 with BASIC auth as the requested way to authenticate and a content-type of text/html. This is very different from my testing system - when I attempt to make a request before authorizing, I instead get a 200 response, content-type of text/xml, and in the body of the XML contents, receive the real response code:
```
2022/12/17 17:04:04 netgear_client.go: Response code: 200
2022/12/17 17:04:04 netgear_client.go: Response headers:
2022/12/17 17:04:04 netgear_client.go:   Content-Type: text/xml; charset="UTF-8"
2022/12/17 17:04:04 netgear_client.go:   Date: Sat, 17 Dec 2022 23:04:04 GMT
2022/12/17 17:04:04 netgear_client.go:   Content-Length: 389
2022/12/17 17:04:04 netgear_client.go:   Server: Linux/2.6.15 uhttpd/1.0.0 soap/1.0
2022/12/17 17:04:04 netgear_client.go: BODY:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
   xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
   SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<SOAP-ENV:Body>
<m:GetSystemInfoResponse xmlns:m="urn:NETGEAR-ROUTER:service:DeviceInfo:1"></m:GetSystemInfoResponse>
<ResponseCode>401</ResponseCode>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Your inclination that perhaps the URL is incorrect seems like a possible issue... but the URL that works on my system is `https://{router_ip}/soap/server_sa/` - which is what you have as well.

My best guess is that perhaps this particular router (NETGEAR R7000 according to the auth header) doesn't support the Netgear SOAP API.

**Comment by klein5656** [comment]
@DRuggeri I think you are right about the router not supporting the Netgear SOAP API. I'm checking with Netgear and will update you.

Thanks

**Comment by klein5656** [comment]
@DRuggeri this can be closed. I'm almost positive my router is not compatible. 

Thank you for your help!

**Comment by DRuggeri** [comment]
All good, @klein5656 

Cheers
