### ISSUE TITLE
Supporting docker releases

### ISSUE THREAD

**Issue by AndreyNikiforov** [DRuggeri/netgear_exporter#3]
Are there any plans to support docker images in addition to binaries for releases?

**Comment by DRuggeri** [comment]
Thanks to @jcwimer, this is documented in the README now.

Does the format provided work for you, @AndreyNikiforov ? Another option would be to maintain an "official" image, but that's probably more than is needed.

**Comment by AndreyNikiforov** [comment]
@DRuggeri I ended up with very similar Dockerfile:
```
FROM golang as build

RUN go get github.com/DRuggeri/netgear_exporter
RUN go build github.com/DRuggeri/netgear_exporter

FROM gcr.io/distroless/base

WORKDIR /app
COPY --from=build /go/netgear_exporter .

ENTRYPOINT ["/app/netgear_exporter"]
```
Building image is not a bit deal once I added build step into my workflows. Since I am using dockerized version of netgear exporter, avoiding build altogether sounded nice.

Closing.
