### ISSUE TITLE
traffic.calculatedelta does not work

### ISSUE THREAD

**Issue by AndreyNikiforov** [DRuggeri/netgear_exporter#5]
Cannot make traffic.calculatedelta working either with parameter or with env var. Don't see any related code either. If it is not implemented yet, pls update readme.

**Comment by DRuggeri** [comment]
Wow - that's embarrassing... thank you for detecting the error! I've fixed this in 0d0f2f0

For reference, if you're looking to recreate a better traffic graph with only the in/out, I was able to achieve the same results on the Prometheus side with this query:
`clamp_min(idelta(netgear_traffic_todayupload[2m]), 0)`

Note the time range of 2m. This should be twice the amount of time your scraping interval is (i.e. if you scrape every 30s, it should be 1m)
