### ISSUE TITLE
Multiple netgear devices?

### ISSUE THREAD

**Issue by DanielWeeber** [DRuggeri/netgear_exporter#9]
Isn't it possible to target multiple netgear devices with only one running instance of this exporter?

**Comment by DRuggeri** [comment]
Hi, @DanielWeeber - thanks for checking in! I'm afraid that is not possible with the code base as it is today. To support this, it would need to be modified to permit overriding each parameter from HTTP request parameters. I've done this on another exporter ([NUT exporter](https://github.com/DRuggeri/nut_exporter/blob/master/nut_exporter.go)) if you would be interested in taking a look and creating a PR to duplicate the functionality.
